remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: 'www.zakodachi.dev'
description: "my notes"
baseurl: "/"
url: "https://www.zakodachi.dev"

header_pages:
  - README.md
  - blog.md